import { describe, expect, it } from "vitest";
import {
  RUNBOOK_CHECKPOINT_PAYLOAD_TYPE,
  dssePreAuthenticationEncoding,
  verifyCheckpoint,
} from "./checkpoint.js";

// Public verification fixture derived from the published RFC 8032 Ed25519 test key.
// The corresponding private material is neither present nor generated by this suite.
const PUBLIC_KEY_BASE64 = "MCowBQYDK2VwAyEA11qYAYKxCrfVS/7TyWQHOg7hcvPapiMlrwIaaPcHURo=";
const KEY_ID = "sha256:06e3fd8fda29bb60ab59557de61edb0aecdb231134be30e75b455f8e1b792fa9";
const SIGNATURE_BASE64 = "KigeXcCmcmy11BDcblONF9zxmAAQoMT1vxNo4exrEs7BDv8s8GHwXcwZbQXCDm6MDtee2wty7r9WwfRBt2x7DQ==";
const LIVE_SIGNATURE_BASE64 = "s/D32uMMR5tBt3MlHT04Lmm20EySqYg+oGZmO9FWmB6yzQ/jMapM63IJe+sL2TIIBO/RQnMqRFknHUZj0Z/lCA==";

function statementBytes(dataClass: "synthetic" | "live-author-declared" = "synthetic") {
  return Buffer.from(JSON.stringify({
    schemaVersion: "runbook.checkpoint.v1",
    experimentDigest: "a".repeat(64),
    checkpointSequence: 1,
    createdAt: "2026-07-21T18:00:00.000Z",
    dataClass,
    authorKeyId: KEY_ID,
    eventChain: {
      algorithm: "runbook-jsonl-chain-v1",
      eventCount: 3,
      headHash: "b".repeat(64),
    },
    proofScope: {
      privacy: "metadata-only",
      sourceCoverage: "author-declared",
      underlyingRecordsIncluded: false,
      independentlyRecomputable: false,
      brokerAttestation: "absent",
    },
    assurancePolicy: "runbook.checkpoint-assurance.v1",
  }));
}

type Envelope = {
  payload: string;
  payloadType: string;
  signatures: [{ keyid: string; sig: string }];
};

function envelope(payload = statementBytes(), signature = SIGNATURE_BASE64): Envelope {
  return {
    payload: payload.toString("base64"),
    payloadType: RUNBOOK_CHECKPOINT_PAYLOAD_TYPE,
    signatures: [{ keyid: KEY_ID, sig: signature }],
  };
}

function input(envelopeValue: Envelope | string = envelope(), statement = statementBytes(), publicKey = Buffer.from(PUBLIC_KEY_BASE64, "base64")) {
  return {
    envelopeJson: Buffer.from(typeof envelopeValue === "string" ? envelopeValue : JSON.stringify(envelopeValue)),
    statementJson: statement,
    publicKeySpkiDer: publicKey,
  };
}

function urlSafe(value: string) {
  return value.replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

describe("dssePreAuthenticationEncoding", () => {
  it("matches the DSSE v1 protocol test vector framing", () => {
    expect(dssePreAuthenticationEncoding("http://example.com/HelloWorld", Buffer.from("hello world")).toString())
      .toBe("DSSEv1 29 http://example.com/HelloWorld 11 hello world");
  });
});

describe("verifyCheckpoint", () => {
  it("verifies exact statement bytes, payload type, fingerprint, and Ed25519 signature", () => {
    const result = verifyCheckpoint(input());

    expect(result.valid).toBe(true);
    expect(result.checkpointId).toMatch(/^[a-f0-9]{64}$/);
    expect(result.publicKeyFingerprint).toBe(KEY_ID);
    expect(result.statement).toMatchObject({
      dataClass: "synthetic",
      proofScope: { privacy: "metadata-only", brokerAttestation: "absent" },
    });
    expect(result.assurance).toMatchObject({
      payloadBinding: "valid",
      authorSignature: "valid",
      authorIdentity: "self-asserted-key",
      eventChain: "author-signed-commitment-only",
      brokerIssuance: "not-evaluated",
      brokerExecution: "not-evaluated",
      recordCompleteness: "not-evaluated",
    });
    expect(result.limitations).toEqual([
      "signature-does-not-prove-broker-issuance",
      "checkpoint-does-not-prove-execution",
      "checkpoint-does-not-prove-record-completeness",
      "checkpoint-does-not-prove-investment-skill",
    ]);
  });

  it("produces a deterministic byte-identical JSON result for identical inputs", () => {
    expect(JSON.stringify(verifyCheckpoint(input()))).toBe(JSON.stringify(verifyCheckpoint(input())));
  });

  it("accepts DSSE-standard URL-safe unpadded base64", () => {
    const value = envelope();
    value.payload = urlSafe(value.payload);
    value.signatures[0].sig = urlSafe(value.signatures[0].sig);

    expect(verifyCheckpoint(input(value)).valid).toBe(true);
  });

  it("rejects mixed standard and URL-safe base64 alphabets", () => {
    const value = envelope();
    value.signatures[0].sig = "AA+_";

    expect(verifyCheckpoint(input(value)).errors).toContain("envelope.schema-invalid");
  });

  it("rejects a one-byte mutation of the supplied statement even when the envelope signature remains valid", () => {
    const mutated = statementBytes();
    mutated[10] = mutated[10] === 65 ? 66 : 65;
    const result = verifyCheckpoint(input(envelope(), mutated));

    expect(result.valid).toBe(false);
    expect(result.assurance.payloadBinding).toBe("invalid");
    expect(result.assurance.authorSignature).toBe("valid");
    expect(result.errors).toContain("payload.byte-mismatch");
  });

  it("rejects a payload-byte mutation even when the mutated bytes are valid statement JSON", () => {
    const mutated = Buffer.concat([statementBytes(), Buffer.from(" ")]);
    const result = verifyCheckpoint(input(envelope(mutated), mutated));

    expect(result.assurance.payloadBinding).toBe("valid");
    expect(result.assurance.statementSchema).toBe("valid");
    expect(result.assurance.authorSignature).toBe("invalid");
    expect(result.errors).toContain("signature.invalid");
  });

  it("binds payload type through PAE and rejects replay under another type", () => {
    const value = envelope();
    value.payloadType = "application/vnd.runbook.other+json;version=1";
    const result = verifyCheckpoint(input(value));

    expect(result.assurance.payloadType).toBe("invalid");
    expect(result.assurance.authorSignature).toBe("invalid");
    expect(result.errors).toEqual(expect.arrayContaining(["payload.type-unsupported", "signature.invalid"]));
  });

  it("rejects signature substitution", () => {
    const value = envelope();
    const signature = Buffer.from(value.signatures[0].sig, "base64");
    signature[0] = (signature[0] as number) ^ 1;
    value.signatures[0].sig = signature.toString("base64");
    const result = verifyCheckpoint(input(value));

    expect(result.assurance.authorSignature).toBe("invalid");
    expect(result.errors).toContain("signature.invalid");
  });

  it("does not trust the unauthenticated DSSE keyid as a key selector", () => {
    const value = envelope();
    value.signatures[0].keyid = `sha256:${"c".repeat(64)}`;
    const result = verifyCheckpoint(input(value));

    expect(result.assurance.authorSignature).toBe("valid");
    expect(result.assurance.keyFingerprint).toBe("invalid");
    expect(result.errors).toContain("key.fingerprint-mismatch");
  });

  it("rejects a different Ed25519 public key", () => {
    const otherEd25519Spki = Buffer.concat([
      Buffer.from("302a300506032b6570032100", "hex"),
      Buffer.from("3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c", "hex"),
    ]);
    const result = verifyCheckpoint(input(envelope(), statementBytes(), otherEd25519Spki));

    expect(result.assurance.publicKey).toBe("valid");
    expect(result.assurance.keyFingerprint).toBe("invalid");
    expect(result.assurance.authorSignature).toBe("invalid");
  });

  it("rejects a non-Ed25519 public key", () => {
    const p256Spki = Buffer.from(
      "3059301306072a8648ce3d020106082a8648ce3d0301070342000467cd390f77aa359cb08c2235f652270493a9ed832b0abcc01f70954c0390d2380c782bd54e269125a44f4433aff1432ce94e12bca73aa67ac80cea12608ddf74",
      "hex",
    );
    const result = verifyCheckpoint(input(envelope(), statementBytes(), p256Spki));

    expect(result.assurance.publicKey).toBe("invalid");
    expect(result.errors).toContain("key.algorithm-unsupported");
  });

  it("strictly rejects unknown envelope and statement fields", () => {
    const extraEnvelope = { ...envelope(), version: 1 };
    const extraStatement = Buffer.from(JSON.stringify({ ...JSON.parse(statementBytes().toString()), note: "not allowed" }));
    const envelopeResult = verifyCheckpoint(input(extraEnvelope as Envelope));
    const statementResult = verifyCheckpoint(input(envelope(extraStatement), extraStatement));

    expect(envelopeResult.errors).toContain("envelope.schema-invalid");
    expect(statementResult.errors).toContain("statement.schema-invalid");
  });

  it("rejects credential-shaped fields before ordinary schema validation", () => {
    const credentialStatement = Buffer.from(JSON.stringify({
      ...JSON.parse(statementBytes().toString()),
      apiKey: "redacted",
    }));
    const result = verifyCheckpoint(input(envelope(credentialStatement), credentialStatement));
    const credentialEnvelope = JSON.stringify({
      ...envelope(),
      privateKey: "redacted",
    });
    const envelopeResult = verifyCheckpoint(input(credentialEnvelope));

    expect(result.errors).toContain("statement.credential-shaped-field");
    expect(result.errors).not.toContain("statement.schema-invalid");
    expect(envelopeResult.errors).toContain("envelope.credential-shaped-field");
    expect(envelopeResult.errors).not.toContain("envelope.schema-invalid");
  });

  it("rejects duplicate JSON keys in both envelope and signed statement", () => {
    const duplicateStatement = Buffer.from(statementBytes().toString().replace(
      "{",
      '{"schemaVersion":"runbook.checkpoint.v1",',
    ));
    const value = envelope(duplicateStatement);
    const duplicateEnvelope = JSON.stringify(value).replace(
      "{",
      `{"payload":${JSON.stringify(value.payload)},`,
    );

    expect(verifyCheckpoint(input(value, duplicateStatement)).errors).toContain("statement.duplicate-key");
    expect(verifyCheckpoint(input(duplicateEnvelope, duplicateStatement)).errors).toContain("envelope.duplicate-key");
  });

  it("rejects malformed UTF-8 and bounded oversized inputs without throwing", () => {
    const invalidUtf8 = verifyCheckpoint({
      ...input(),
      envelopeJson: Buffer.from([0xc3, 0x28]),
    });
    const oversized = verifyCheckpoint({
      ...input(),
      statementJson: Buffer.alloc(64 * 1024 + 1),
    });

    expect(invalidUtf8.errors).toContain("envelope.invalid-utf8");
    expect(oversized.errors).toContain("input.statement-size-invalid");
  });

  it("never upgrades broker assurance for a live author declaration", () => {
    const liveStatement = statementBytes("live-author-declared");
    const result = verifyCheckpoint(input(envelope(liveStatement, LIVE_SIGNATURE_BASE64), liveStatement));

    expect(result.valid).toBe(true);
    expect(result.statement?.dataClass).toBe("live-author-declared");
    expect(result.assurance.brokerIssuance).toBe("not-evaluated");
    expect(result.assurance.brokerExecution).toBe("not-evaluated");
    expect(result.assurance.recordCompleteness).toBe("not-evaluated");
  });
});
